name: 'Setup Flutter'
description: 'Setup Flutter SDK and install dependencies for client'

inputs:
  flutter-version:
    description: 'Flutter version'
    required: false
    default: '3.38.4'
  channel:
    description: 'Flutter channel'
    required: false
    default: 'stable'
  google-maps-api-key:
    description: 'Google Maps API Key'
    required: false
    default: 'placeholder'

runs:
  using: 'composite'
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.channel }}
        cache: true
    
    - name: Create temporary .env file
      run: echo "GOOGLE_MAPS_API_KEY=${{ inputs.google-maps-api-key }}" > frontend/client/.env
      shell: bash

    - name: Install dependencies
      run: flutter pub get
      shell: bash
      working-directory: frontend/client